# Generated by Django 5.2.4 on 2025-07-14 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.RESTRICT, to='core.vendor'),
        ),
    ]
