# Generated by Django 5.2.4 on 2025-07-21 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_address_mobile_alter_cartorder_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='wishlist_model',
        ),
    ]
