# Generated by Django 5.2.4 on 2025-07-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupon',
            new_name='Coupon',
        ),
    ]
