# Generated by Django 5.2.4 on 2025-07-27 19:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_cartorder_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='Contenido', null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
