# Generated by Django 5.2.4 on 2025-07-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_status',
            field=models.BooleanField(default=False),
        ),
    ]
