# Generated by Django 5.2.4 on 2025-07-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_cartorderitems_cartorderproducts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'En Proceso'), ('shipped', 'Enviado'), ('delivered', 'Entregado')], default='Procesando'),
        ),
    ]
