# Generated by Django 5.2.4 on 2025-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cartorder_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(blank=True, choices=[('processing', 'En Proceso'), ('shipped', 'Enviado'), ('delivered', 'Entregado')], default='Procesando', null=True),
        ),
    ]
